package com.thingtrack.konekti.view.module.sensor.internal;

import com.thingtrack.konekti.service.sensor.api.SensorLocationService;
import com.thingtrack.konekti.service.sensor.api.SensorMessageService;
import com.thingtrack.konekti.service.sensor.api.SensorService;
import com.thingtrack.konekti.service.sensor.api.SensorTelemetryService;
import com.thingtrack.konekti.view.addon.ui.AbstractView;
import com.thingtrack.konekti.view.addon.ui.DataGridView;
import com.thingtrack.konekti.view.kernel.IWorkbenchContext;
import com.thingtrack.konekti.view.kernel.ui.layout.IViewContainer;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class SensorView extends AbstractView {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private DataGridView dgSensor;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private IViewContainer viewContainer;
	private IWorkbenchContext context;
	
	private SensorMessageService sensorMessageService;
	private SensorLocationService sensorLocationService;
	private SensorTelemetryService sensorTelemetryService;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SensorView(IWorkbenchContext context, IViewContainer viewContainer) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.context = context;
		
		// set Slide View Services and ViewContainer to navigate
		this.viewContainer = viewContainer;
		
		this.sensorMessageService = SensorViewContainer.getSensorMessageService();
		this.sensorLocationService = SensorViewContainer.getSensorLocationService();
		this.sensorTelemetryService = SensorViewContainer.getSensorTelemetryService();
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// dataGridView_1
		dgSensor = new DataGridView();
		dgSensor.setImmediate(false);
		dgSensor.setWidth("100.0%");
		dgSensor.setHeight("100.0%");
		mainLayout.addComponent(dgSensor);
		mainLayout.setExpandRatio(dgSensor, 1.0f);
		
		return mainLayout;
	}

}
