package com.thingtrack.konekti.view.web.form.field;

import org.vaadin.addon.customfield.CustomField;

import com.thingtrack.konekti.domain.Action;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class ActionTwinTableField extends CustomField {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout editToolBar;
	@AutoGenerated
	private Button btnRemoveRegister;
	@AutoGenerated
	private Button btnEditRegister;
	@AutoGenerated
	private Button btnAddRegister;
	@AutoGenerated
	private VerticalLayout aux2Layout;
	@AutoGenerated
	private Table tbAvailableRegister;
	@AutoGenerated
	private VerticalLayout moveToolbar;
	@AutoGenerated
	private Button btnSetAllRegister;
	@AutoGenerated
	private Button btnSetRegister;
	@AutoGenerated
	private Button btnUnsetRegister;
	@AutoGenerated
	private Button btnUnsetAllRegister;
	@AutoGenerated
	private VerticalLayout auxLayout;
	@AutoGenerated
	private Table tbActiveRegisters;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private BeanItemContainer<Action> dsActiveActions;
	private BeanItemContainer<Action> dsAvailableActions;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ActionTwinTableField() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		btnSetAllRegister.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
			}
		});
		
		btnSetRegister.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
			}
		});
		
		btnUnsetRegister.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
			}
		});
		
		btnUnsetAllRegister.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
			}
		});
	
		btnAddRegister.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
			}
		});
		
		btnEditRegister.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
			}
		});
		
		btnRemoveRegister.addListener(new ClickListener() {			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
			}
		});		
	}

	public void setActiveRegisterDataSource(BeanItemContainer<Action> datasource) {
		this.dsActiveActions = datasource;
		
	}

	public void setAvailableRegisterDataSource(BeanItemContainer<Action> datasource) {
		this.dsAvailableActions = datasource;
		
	}
	
	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// tbActiveRegisters
		tbActiveRegisters = new Table();
		tbActiveRegisters.setCaption("Activos");
		tbActiveRegisters.setImmediate(false);
		tbActiveRegisters.setWidth("180px");
		tbActiveRegisters.setHeight("-1px");
		mainLayout.addComponent(tbActiveRegisters);
		
		// moveToolbar
		moveToolbar = buildMoveToolbar();
		mainLayout.addComponent(moveToolbar);
		
		// tbAvailableRegister
		tbAvailableRegister = new Table();
		tbAvailableRegister.setCaption("Disponibles");
		tbAvailableRegister.setImmediate(false);
		tbAvailableRegister.setWidth("180px");
		tbAvailableRegister.setHeight("-1px");
		mainLayout.addComponent(tbAvailableRegister);
		
		// editToolBar
		editToolBar = buildEditToolBar();
		mainLayout.addComponent(editToolBar);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildMoveToolbar() {
		// common part: create layout
		moveToolbar = new VerticalLayout();
		moveToolbar.setImmediate(false);
		moveToolbar.setWidth("50px");
		moveToolbar.setHeight("100.0%");
		moveToolbar.setMargin(false);
		
		// auxLayout
		auxLayout = new VerticalLayout();
		auxLayout.setImmediate(false);
		auxLayout.setWidth("100.0%");
		auxLayout.setHeight("50px");
		auxLayout.setMargin(false);
		moveToolbar.addComponent(auxLayout);
		
		// btnUnsetAllRegister
		btnUnsetAllRegister = new Button();
		btnUnsetAllRegister.setCaption("->>");
		btnUnsetAllRegister.setImmediate(true);
		btnUnsetAllRegister.setWidth("100.0%");
		btnUnsetAllRegister.setHeight("-1px");
		moveToolbar.addComponent(btnUnsetAllRegister);
		
		// btnUnsetRegister
		btnUnsetRegister = new Button();
		btnUnsetRegister.setCaption("->");
		btnUnsetRegister.setImmediate(true);
		btnUnsetRegister.setWidth("100.0%");
		btnUnsetRegister.setHeight("-1px");
		moveToolbar.addComponent(btnUnsetRegister);
		
		// btnSetRegister
		btnSetRegister = new Button();
		btnSetRegister.setCaption("<-");
		btnSetRegister.setImmediate(true);
		btnSetRegister.setWidth("100.0%");
		btnSetRegister.setHeight("-1px");
		moveToolbar.addComponent(btnSetRegister);
		
		// btnSetAllRegister
		btnSetAllRegister = new Button();
		btnSetAllRegister.setCaption("<<-");
		btnSetAllRegister.setImmediate(true);
		btnSetAllRegister.setWidth("100.0%");
		btnSetAllRegister.setHeight("-1px");
		moveToolbar.addComponent(btnSetAllRegister);
		moveToolbar.setExpandRatio(btnSetAllRegister, 1.0f);
		
		return moveToolbar;
	}

	@AutoGenerated
	private VerticalLayout buildEditToolBar() {
		// common part: create layout
		editToolBar = new VerticalLayout();
		editToolBar.setImmediate(false);
		editToolBar.setWidth("50px");
		editToolBar.setHeight("100.0%");
		editToolBar.setMargin(false);
		
		// aux2Layout
		aux2Layout = new VerticalLayout();
		aux2Layout.setImmediate(false);
		aux2Layout.setWidth("100.0%");
		aux2Layout.setHeight("50px");
		aux2Layout.setMargin(false);
		editToolBar.addComponent(aux2Layout);
		
		// btnAddRegister
		btnAddRegister = new Button();
		btnAddRegister.setCaption("+");
		btnAddRegister.setImmediate(true);
		btnAddRegister.setWidth("100.0%");
		btnAddRegister.setHeight("-1px");
		editToolBar.addComponent(btnAddRegister);
		
		// btnEditRegister
		btnEditRegister = new Button();
		btnEditRegister.setCaption("U");
		btnEditRegister.setImmediate(true);
		btnEditRegister.setWidth("100.0%");
		btnEditRegister.setHeight("-1px");
		editToolBar.addComponent(btnEditRegister);
		
		// btnRemoveRegister
		btnRemoveRegister = new Button();
		btnRemoveRegister.setCaption("-");
		btnRemoveRegister.setImmediate(true);
		btnRemoveRegister.setWidth("100.0%");
		btnRemoveRegister.setHeight("-1px");
		editToolBar.addComponent(btnRemoveRegister);
		editToolBar.setExpandRatio(btnRemoveRegister, 1.0f);
		
		return editToolBar;
	}

	@Override
	public Class<?> getType() {
		// TODO Auto-generated method stub
		return null;
	}

}
