package com.thingtrack.konekti.view.web.form.field;

import org.vaadin.addon.customfield.CustomField;

import com.thingtrack.konekti.domain.Product;
import com.thingtrack.konekti.view.web.form.selector.ProductSelectorWindow;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;

@SuppressWarnings("serial")
public class ProductSelectorField extends CustomField {
	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Button btnSearch;
	@AutoGenerated
	private TextField productField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private Product product;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ProductSelectorField() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		productField.setNullRepresentation("");
		productField.setRequiredError(productField.getCaption() + " es un campo requerido");
		
		btnSearch.addListener(new ClickListener() {			
			@Override
			public void buttonClick(ClickEvent event) {
				try {
					@SuppressWarnings("unused")
					ProductSelectorWindow windowDialog = new ProductSelectorWindow(getApplication().getMainWindow(), product, new ProductSelectorWindow.CloseWindowDialogListener() {
					    public void windowDialogClose(ProductSelectorWindow.CloseWindowDialogEvent event) {
					    	if (event.getDialogResult() != ProductSelectorWindow.DialogResult.SELECT)
					    		return ;
					    	
					    	product = event.getDomainEntity();
					    	productField.setValue(product.getName());
					    }
		
					});
				} catch (Exception e) {
					throw new RuntimeException("¡No se pudo abrir el selector de productos!", e);
				}
			}
		});
	}

	@Override
	public void setPropertyDataSource(Property newDataSource) {
		product = (Product) newDataSource.getValue();

		if (product != null)
			productField.setValue(product.getName());
		
		super.setPropertyDataSource(newDataSource);
	}
	
	@Override
	public Object getValue() {
		return product;
	}
	
	@Override
	public Class<?> getType() {
		return Product.class;
		
	}
	
	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("28px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("28px");
		
		// holeField
		productField = new TextField();
		productField.setImmediate(false);
		productField.setWidth("150px");
		productField.setHeight("-1px");
		mainLayout.addComponent(productField);
		
		// btnSearch
		btnSearch = new Button();
		btnSearch.setIcon(new ThemeResource("../konekti/images/icons/container-module/magnifier-zoom.png"));
		btnSearch.setImmediate(true);
		btnSearch.setWidth("-1px");
		btnSearch.setHeight("-1px");
		mainLayout.addComponent(btnSearch);
		mainLayout.setExpandRatio(btnSearch, 1.0f);
		
		return mainLayout;
	}

}
