package com.thingtrack.konekti.view.web.form;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class AlarmViewForm extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private ComboBox alarmStatusField;
	@AutoGenerated
	private ComboBox alarmTypeField;
	@AutoGenerated
	private TextField organizationField;
	@AutoGenerated
	private TextField messageField;
	@AutoGenerated
	private TextField areaField;
	@AutoGenerated
	private DateField alarmDateField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public AlarmViewForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("520px");
		mainLayout.setHeight("280px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("520px");
		setHeight("280px");
		
		// alarmDateField
		alarmDateField = new DateField();
		alarmDateField.setCaption("Fecha alarma");
		alarmDateField.setImmediate(false);
		alarmDateField.setWidth("120px");
		alarmDateField.setHeight("-1px");
		alarmDateField.setInvalidAllowed(false);
		alarmDateField.setResolution(DateField.RESOLUTION_SEC);
		mainLayout.addComponent(alarmDateField, "top:17.0px;left:380.0px;");
		
		// areaField
		areaField = new TextField();
		areaField.setCaption("Area trabajo");
		areaField.setImmediate(false);
		areaField.setWidth("160px");
		areaField.setHeight("-1px");
		mainLayout.addComponent(areaField, "top:17.0px;left:200.0px;");
		
		// messageField
		messageField = new TextField();
		messageField.setCaption("Message");
		messageField.setImmediate(false);
		messageField.setWidth("480px");
		messageField.setHeight("164px");
		mainLayout.addComponent(messageField, "top:100.0px;left:20.0px;");
		
		// organizationField
		organizationField = new TextField();
		organizationField.setCaption("Organización");
		organizationField.setImmediate(false);
		organizationField.setWidth("160px");
		organizationField.setHeight("-1px");
		mainLayout.addComponent(organizationField, "top:17.0px;left:20.0px;");
		
		// alarmTypeField
		alarmTypeField = new ComboBox();
		alarmTypeField.setCaption("Tipo alarma");
		alarmTypeField.setImmediate(false);
		alarmTypeField.setWidth("180px");
		alarmTypeField.setHeight("-1px");
		mainLayout.addComponent(alarmTypeField, "top:60.0px;left:20.0px;");
		
		// alarmStatusField
		alarmStatusField = new ComboBox();
		alarmStatusField.setCaption("Estado alarma");
		alarmStatusField.setImmediate(false);
		alarmStatusField.setWidth("180px");
		alarmStatusField.setHeight("-1px");
		mainLayout.addComponent(alarmStatusField, "top:60.0px;left:220.0px;");
		
		return mainLayout;
	}
}