package com.thingtrack.konekti.view.web.form;

import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceReference;

import com.thingtrack.konekti.domain.Client;
import com.thingtrack.konekti.domain.ClientGroup;
import com.thingtrack.konekti.domain.ClientType;
import com.thingtrack.konekti.service.api.ClientGroupService;
import com.thingtrack.konekti.service.api.ClientTypeService;
import com.thingtrack.konekti.view.addon.data.BindingSource;
import com.thingtrack.konekti.view.addon.ui.WindowDialog;
import com.thingtrack.konekti.view.web.form.field.AddressField;
import com.thingtrack.konekti.view.web.form.field.AddressField.AddressChangeEvent;
import com.thingtrack.konekti.view.web.form.field.AddressField.AddressChangeListener;
import com.thingtrack.konekti.view.web.form.field.ClientAgentCollectionField;
import com.thingtrack.konekti.view.web.form.field.ClientOrganizationCollectionField;
import com.thingtrack.konekti.view.web.form.field.ImageField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Select;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class ClientViewForm extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private ImageField photoField;
	@AutoGenerated
	private TextField emailField;
	@AutoGenerated
	private TextField facebookIdField;
	@AutoGenerated
	private TextField mobileField;
	@AutoGenerated
	private TextField faxField;
	@AutoGenerated
	private TextField phoneField;
	@AutoGenerated
	private ClientAgentCollectionField clientAgentsField;
	@AutoGenerated
	private ClientOrganizationCollectionField organizationsField;
	@AutoGenerated
	private ComboBox clientGroupField;
	@AutoGenerated
	private ComboBox clientTypeField;
	@AutoGenerated
	private TextField nameField;
	@AutoGenerated
	private TextField descriptionField;
	@AutoGenerated
	private TextField commentField;
	@AutoGenerated
	private TextField codeField;
	@AutoGenerated
	private AddressField clientAddressField;
	@AutoGenerated
	private TextField vatField;
	@AutoGenerated
	private CheckBox activeField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	// form services
	private ClientTypeService clientTypeService;
	private ClientGroupService clientGroupService;
	
	// client type datasource
	private BeanItemContainer<ClientType> bcClientType = new BindingSource<ClientType>(ClientType.class);
	private BeanItemContainer<ClientGroup> bcClientGroup = new BindingSource<ClientGroup>(ClientGroup.class);
	
	private Client client;
	
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 * @throws Exception 
	 * @throws IllegalArgumentException 
	 */
	public ClientViewForm() throws IllegalArgumentException, Exception {		
		 
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		initComponents();
		
		// configure Organization Type data
		clientTypeField.setItemCaptionMode(Select.ITEM_CAPTION_MODE_PROPERTY);
		clientTypeField.setItemCaptionPropertyId("description");
		
		clientGroupField.setItemCaptionMode(Select.ITEM_CAPTION_MODE_PROPERTY);
		clientGroupField.setItemCaptionPropertyId("description");
		
		clientAddressField.addListenerAddressChange(new AddressChangeListener() {			
			@Override
			public void addressChange(AddressChangeEvent event) {
				if (client != null)
					client.setClientAddress(event.getAddress());
				
			}
		});
		
		// get form services from OSGi Service Registry
		getServices();
		
		// load data sources
		loadData();
		
	}
		
	private void initComponents() {
		nameField.setNullRepresentation("");
		descriptionField.setNullRepresentation("");
		commentField.setNullRepresentation("");
		codeField.setNullRepresentation("");
		vatField.setNullRepresentation("");
		phoneField.setNullRepresentation("");
		faxField.setNullRepresentation("");
		mobileField.setNullRepresentation("");
		facebookIdField.setNullRepresentation("");
		emailField.setNullRepresentation("");
		
		organizationsField.setCaption("Organizaciones");
		clientAgentsField.setCaption("Contactos");
		
		codeField.setRequiredError(codeField.getCaption() + " es un campo requerido");
		clientGroupField.setRequiredError(clientGroupField.getCaption() + " es un campo requerido");
		clientTypeField.setRequiredError(clientTypeField.getCaption() + " es un campo requerido");
	}
	
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void getServices() {
		try {
			BundleContext bundleContext = FrameworkUtil.getBundle(ClientViewForm.class).getBundleContext();
			
			ServiceReference clientTypeServiceReference = bundleContext.getServiceReference(ClientTypeService.class.getName());
			clientTypeService = ClientTypeService.class.cast(bundleContext.getService(clientTypeServiceReference));
			
			ServiceReference clientGroupServiceReference = bundleContext.getServiceReference(ClientGroupService.class.getName());
			clientGroupService = ClientGroupService.class.cast(bundleContext.getService(clientGroupServiceReference));
		}
		catch (Exception e) {
			e.getMessage();
			
		}
		
	}
	
	private void loadData() throws IllegalArgumentException, Exception {		
		bcClientType.removeAllItems();
		bcClientType.addAll(clientTypeService.getAll());
		
		clientTypeField.setContainerDataSource(bcClientType);
		
		bcClientGroup.removeAllItems();
		bcClientGroup.addAll(clientGroupService.getAll());
		
		clientGroupField.setContainerDataSource(bcClientGroup);
		
	}
	
	@Override
    public void attach() {
		super.attach();
		
		// recover the parent entity (Client) from parent view window (ClientViewForm)
		if (getParent().getWindow() instanceof WindowDialog<?>) {
			@SuppressWarnings("unchecked")
			WindowDialog<Client> clientWindowDialog = (WindowDialog<Client>)getParent().getWindow();
			client = clientWindowDialog.getDomainEntity();    			
		}
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("920px");
		mainLayout.setHeight("500px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("920px");
		setHeight("500px");
		
		// activeField
		activeField = new CheckBox();
		activeField.setCaption("Activo");
		activeField.setImmediate(false);
		activeField.setWidth("-1px");
		activeField.setHeight("-1px");
		activeField.setTabIndex(3);
		activeField.setRequired(true);
		mainLayout.addComponent(activeField, "top:20.0px;left:847.0px;");
		
		// vatField
		vatField = new TextField();
		vatField.setCaption("CIF/NIF");
		vatField.setImmediate(false);
		vatField.setWidth("80px");
		vatField.setHeight("-1px");
		vatField.setTabIndex(6);
		mainLayout.addComponent(vatField, "top:57.0px;left:461.0px;");
		
		// clientAddressField
		clientAddressField = new AddressField();
		clientAddressField.setCaption("Dirección cliente");
		clientAddressField.setImmediate(false);
		clientAddressField.setWidth("421px");
		clientAddressField.setHeight("120px");
		clientAddressField.setRequired(true);
		mainLayout.addComponent(clientAddressField, "top:180.0px;left:20.0px;");
		
		// codeField
		codeField = new TextField();
		codeField.setCaption("Código");
		codeField.setImmediate(false);
		codeField.setWidth("79px");
		codeField.setHeight("-1px");
		codeField.setTabIndex(1);
		codeField.setRequired(true);
		mainLayout.addComponent(codeField, "top:17.0px;left:461.0px;");
		
		// commentField
		commentField = new TextField();
		commentField.setCaption("Comentario");
		commentField.setImmediate(false);
		commentField.setWidth("420px");
		commentField.setHeight("42px");
		commentField.setTabIndex(8);
		mainLayout.addComponent(commentField, "top:318.0px;left:21.0px;");
		
		// descriptionField
		descriptionField = new TextField();
		descriptionField.setCaption("Descripción");
		descriptionField.setImmediate(false);
		descriptionField.setWidth("440px");
		descriptionField.setHeight("-1px");
		descriptionField.setTabIndex(4);
		mainLayout.addComponent(descriptionField, "top:96.0px;left:461.0px;");
		
		// nameField
		nameField = new TextField();
		nameField.setCaption("Nombre Comercial");
		nameField.setImmediate(false);
		nameField.setWidth("261px");
		nameField.setHeight("-1px");
		nameField.setTabIndex(2);
		nameField.setRequired(true);
		mainLayout.addComponent(nameField, "top:17.0px;left:560.0px;");
		
		// clientTypeField
		clientTypeField = new ComboBox();
		clientTypeField.setCaption("Tipo cliente");
		clientTypeField.setImmediate(false);
		clientTypeField.setWidth("160px");
		clientTypeField.setHeight("-1px");
		clientTypeField.setTabIndex(6);
		clientTypeField.setRequired(true);
		mainLayout.addComponent(clientTypeField, "top:57.0px;left:561.0px;");
		
		// clientGroupField
		clientGroupField = new ComboBox();
		clientGroupField.setCaption("Grupo cliente");
		clientGroupField.setImmediate(false);
		clientGroupField.setWidth("160px");
		clientGroupField.setHeight("-1px");
		clientGroupField.setTabIndex(7);
		clientGroupField.setRequired(true);
		mainLayout.addComponent(clientGroupField, "top:60.0px;left:741.0px;");
		
		// organizationsField
		organizationsField = new ClientOrganizationCollectionField();
		organizationsField.setImmediate(false);
		organizationsField.setWidth("444px");
		organizationsField.setHeight("140px");
		mainLayout
				.addComponent(organizationsField, "top:220.0px;left:459.0px;");
		
		// clientAgentsField
		clientAgentsField = new ClientAgentCollectionField();
		clientAgentsField.setImmediate(false);
		clientAgentsField.setWidth("881px");
		clientAgentsField.setHeight("100px");
		mainLayout.addComponent(clientAgentsField, "top:380.0px;left:21.0px;");
		
		// phoneField
		phoneField = new TextField();
		phoneField.setCaption("Teléfono");
		phoneField.setImmediate(false);
		phoneField.setWidth("102px");
		phoneField.setHeight("-1px");
		mainLayout.addComponent(phoneField, "top:137.0px;left:459.0px;");
		
		// faxField
		faxField = new TextField();
		faxField.setCaption("Fax");
		faxField.setImmediate(false);
		faxField.setWidth("100px");
		faxField.setHeight("-1px");
		mainLayout.addComponent(faxField, "top:138.0px;left:581.0px;");
		
		// mobileField
		mobileField = new TextField();
		mobileField.setCaption("Teléfono Móvil");
		mobileField.setImmediate(false);
		mobileField.setWidth("100px");
		mobileField.setHeight("-1px");
		mainLayout.addComponent(mobileField, "top:138.0px;left:701.0px;");
		
		// facebookIdField
		facebookIdField = new TextField();
		facebookIdField.setCaption("Facebook Id");
		facebookIdField.setImmediate(false);
		facebookIdField.setWidth("80px");
		facebookIdField.setHeight("-1px");
		mainLayout.addComponent(facebookIdField, "top:138.0px;left:821.0px;");
		
		// emailField
		emailField = new TextField();
		emailField.setCaption("Email");
		emailField.setImmediate(false);
		emailField.setWidth("442px");
		emailField.setHeight("-1px");
		mainLayout.addComponent(emailField, "top:178.0px;left:459.0px;");
		
		// photoField
		photoField = new ImageField();
		photoField.setImmediate(false);
		photoField.setWidth("420px");
		photoField.setHeight("140px");
		mainLayout.addComponent(photoField, "top:20.0px;left:21.0px;");
		
		return mainLayout;
	}
}
