package com.thingtrack.konekti.view.web.form;

import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceReference;

import com.thingtrack.konekti.domain.Supplier;
import com.thingtrack.konekti.domain.SupplierGroup;
import com.thingtrack.konekti.domain.SupplierType;
import com.thingtrack.konekti.service.api.SupplierGroupService;
import com.thingtrack.konekti.service.api.SupplierTypeService;
import com.thingtrack.konekti.view.addon.data.BindingSource;
import com.thingtrack.konekti.view.addon.ui.WindowDialog;
import com.thingtrack.konekti.view.web.form.field.AddressField;
import com.thingtrack.konekti.view.web.form.field.AddressField.AddressChangeEvent;
import com.thingtrack.konekti.view.web.form.field.AddressField.AddressChangeListener;
import com.thingtrack.konekti.view.web.form.field.ImageField;
import com.thingtrack.konekti.view.web.form.field.SupplierAgentCollectionField;
import com.thingtrack.konekti.view.web.form.field.SupplierOrganizationCollectionField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Select;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class SupplierViewForm extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField facebookIdField;
	@AutoGenerated
	private TextField mobileField;
	@AutoGenerated
	private TextField faxField;
	@AutoGenerated
	private TextField phoneField;
	@AutoGenerated
	private TextField emailField;
	@AutoGenerated
	private ImageField photoField;
	@AutoGenerated
	private SupplierAgentCollectionField supplierAgentsField;
	@AutoGenerated
	private SupplierOrganizationCollectionField organizationsField;
	@AutoGenerated
	private ComboBox supplierGroupField;
	@AutoGenerated
	private ComboBox supplierTypeField;
	@AutoGenerated
	private TextField nameField;
	@AutoGenerated
	private TextField descriptionField;
	@AutoGenerated
	private TextField commentField;
	@AutoGenerated
	private TextField codeField;
	@AutoGenerated
	private AddressField supplierAddressField;
	@AutoGenerated
	private TextField vatField;
	@AutoGenerated
	private CheckBox activeField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	// form services
	private SupplierTypeService supplierTypeService;
	private SupplierGroupService supplierGroupService;
	
	// client type datasource
	private BeanItemContainer<SupplierType> bcSupplierType = new BindingSource<SupplierType>(SupplierType.class);
	private BeanItemContainer<SupplierGroup> bcSupplierGroup = new BindingSource<SupplierGroup>(SupplierGroup.class);
	
	private Supplier supplier;
	
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 * @throws Exception 
	 * @throws IllegalArgumentException 
	 */
	public SupplierViewForm() throws IllegalArgumentException, Exception {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		// configure Organization Type data
		supplierTypeField.setItemCaptionMode(Select.ITEM_CAPTION_MODE_PROPERTY);
		supplierTypeField.setItemCaptionPropertyId("description");
		
		supplierGroupField.setItemCaptionMode(Select.ITEM_CAPTION_MODE_PROPERTY);
		supplierGroupField.setItemCaptionPropertyId("description");
		
		supplierAddressField.addListenerAddressChange(new AddressChangeListener() {			
			@Override
			public void addressChange(AddressChangeEvent event) {
				if (supplier != null)
					supplier.setSupplierAddress(event.getAddress());
				
			}
		});
		
		initComponents();
		
		// get form services from OSGi Service Registry
		getServices();
		
		// load data sources
		loadData();		
	}
	
	private void initComponents() {
		nameField.setNullRepresentation("");
		descriptionField.setNullRepresentation("");
		commentField.setNullRepresentation("");
		codeField.setNullRepresentation("");
		vatField.setNullRepresentation("");
		phoneField.setNullRepresentation("");
		faxField.setNullRepresentation("");
		mobileField.setNullRepresentation("");
		facebookIdField.setNullRepresentation("");
		emailField.setNullRepresentation("");
		
		organizationsField.setCaption("Organizaciones");
		supplierAgentsField.setCaption("Contactos");
		
		codeField.setRequiredError(codeField.getCaption() + " es un campo requerido");
		nameField.setRequiredError(nameField.getCaption() + " es un campo requerido");
		supplierTypeField.setRequiredError(supplierTypeField.getCaption() + " es un campo requerido");
		supplierGroupField.setRequiredError(supplierGroupField.getCaption() + " es un campo requerido");
	}
	
	private void loadData() throws IllegalArgumentException, Exception {		
		bcSupplierType.removeAllItems();
		bcSupplierType.addAll(supplierTypeService.getAll());
		
		supplierTypeField.setContainerDataSource(bcSupplierType);
		
		bcSupplierGroup.removeAllItems();
		bcSupplierGroup.addAll(supplierGroupService.getAll());
		
		supplierGroupField.setContainerDataSource(bcSupplierGroup);
		
	}
	
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void getServices() {
		try {
			BundleContext bundleContext = FrameworkUtil.getBundle(SupplierViewForm.class).getBundleContext();
			
			ServiceReference supplierTypeServiceReference = bundleContext.getServiceReference(SupplierTypeService.class.getName());
			supplierTypeService = SupplierTypeService.class.cast(bundleContext.getService(supplierTypeServiceReference));
			
			ServiceReference supplierGroupServiceReference = bundleContext.getServiceReference(SupplierGroupService.class.getName());
			supplierGroupService = SupplierGroupService.class.cast(bundleContext.getService(supplierGroupServiceReference));
		}
		catch (Exception e) {
			e.getMessage();
			
		}
		
	}
	
	@Override
    public void attach() {  
		// recover the parent entity (Client) from parent view window (ClientViewForm)
		if (getParent().getWindow() instanceof WindowDialog<?>) {
			@SuppressWarnings("unchecked")
			WindowDialog<Supplier> supplierWindowDialog = (WindowDialog<Supplier>)getParent().getWindow();
			supplier = supplierWindowDialog.getDomainEntity();
    		
		}
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("920px");
		mainLayout.setHeight("500px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("920px");
		setHeight("500px");
		
		// activeField
		activeField = new CheckBox();
		activeField.setCaption("Activo");
		activeField.setImmediate(false);
		activeField.setWidth("-1px");
		activeField.setHeight("-1px");
		activeField.setTabIndex(3);
		activeField.setRequired(true);
		mainLayout.addComponent(activeField, "top:20.0px;left:847.0px;");
		
		// cifField
		vatField = new TextField();
		vatField.setCaption("CIF/NIF");
		vatField.setImmediate(false);
		vatField.setWidth("83px");
		vatField.setHeight("-1px");
		vatField.setTabIndex(6);
		vatField.setSecret(false);
		mainLayout.addComponent(vatField, "top:56.0px;left:457.0px;");
		
		// supplierAddressField
		supplierAddressField = new AddressField();
		supplierAddressField.setCaption("Dirección proveedor");
		supplierAddressField.setImmediate(false);
		supplierAddressField.setWidth("420px");
		supplierAddressField.setHeight("120px");
		supplierAddressField.setRequired(true);
		mainLayout.addComponent(supplierAddressField,
				"top:180.0px;left:20.0px;");
		
		// codeField
		codeField = new TextField();
		codeField.setCaption("Código");
		codeField.setImmediate(false);
		codeField.setWidth("79px");
		codeField.setHeight("-1px");
		codeField.setTabIndex(1);
		codeField.setRequired(true);
		codeField.setSecret(false);
		mainLayout.addComponent(codeField, "top:17.0px;left:458.0px;");
		
		// commentField
		commentField = new TextField();
		commentField.setCaption("Comentario");
		commentField.setImmediate(false);
		commentField.setWidth("420px");
		commentField.setHeight("42px");
		commentField.setTabIndex(9);
		commentField.setSecret(false);
		mainLayout.addComponent(commentField, "top:318.0px;left:20.0px;");
		
		// descriptionField
		descriptionField = new TextField();
		descriptionField.setCaption("Descripción");
		descriptionField.setImmediate(false);
		descriptionField.setWidth("442px");
		descriptionField.setHeight("-1px");
		descriptionField.setTabIndex(4);
		descriptionField.setSecret(false);
		mainLayout.addComponent(descriptionField, "top:96.0px;left:458.0px;");
		
		// nameField
		nameField = new TextField();
		nameField.setCaption("Nombre Comercial");
		nameField.setImmediate(false);
		nameField.setWidth("280px");
		nameField.setHeight("-1px");
		nameField.setTabIndex(2);
		nameField.setRequired(true);
		nameField.setSecret(false);
		mainLayout.addComponent(nameField, "top:17.0px;left:560.0px;");
		
		// supplierTypeField
		supplierTypeField = new ComboBox();
		supplierTypeField.setCaption("Tipo proveedor");
		supplierTypeField.setImmediate(false);
		supplierTypeField.setWidth("169px");
		supplierTypeField.setHeight("-1px");
		supplierTypeField.setTabIndex(7);
		supplierTypeField.setRequired(true);
		mainLayout.addComponent(supplierTypeField, "top:57.0px;left:560.0px;");
		
		// supplierGroupField
		supplierGroupField = new ComboBox();
		supplierGroupField.setCaption("Grupo proveedor");
		supplierGroupField.setImmediate(false);
		supplierGroupField.setWidth("160px");
		supplierGroupField.setHeight("-1px");
		supplierGroupField.setTabIndex(8);
		supplierGroupField.setRequired(true);
		mainLayout.addComponent(supplierGroupField, "top:58.0px;left:740.0px;");
		
		// organizationsField
		organizationsField = new SupplierOrganizationCollectionField();
		organizationsField.setImmediate(false);
		organizationsField.setWidth("440px");
		organizationsField.setHeight("140px");
		mainLayout
				.addComponent(organizationsField, "top:220.0px;left:460.0px;");
		
		// supplierAgentsField
		supplierAgentsField = new SupplierAgentCollectionField();
		supplierAgentsField.setImmediate(false);
		supplierAgentsField.setWidth("880px");
		supplierAgentsField.setHeight("100px");
		mainLayout
				.addComponent(supplierAgentsField, "top:380.0px;left:20.0px;");
		
		// photoField
		photoField = new ImageField();
		photoField.setImmediate(false);
		photoField.setWidth("420px");
		photoField.setHeight("140px");
		mainLayout.addComponent(photoField, "top:20.0px;left:20.0px;");
		
		// emailField
		emailField = new TextField();
		emailField.setCaption("Email");
		emailField.setImmediate(false);
		emailField.setWidth("442px");
		emailField.setHeight("-1px");
		emailField.setSecret(false);
		mainLayout.addComponent(emailField, "top:178.0px;left:460.0px;");
		
		// phoneField
		phoneField = new TextField();
		phoneField.setCaption("Teléfono");
		phoneField.setImmediate(false);
		phoneField.setWidth("102px");
		phoneField.setHeight("-1px");
		phoneField.setSecret(false);
		mainLayout.addComponent(phoneField, "top:138.0px;left:458.0px;");
		
		// faxField
		faxField = new TextField();
		faxField.setCaption("Fax");
		faxField.setImmediate(false);
		faxField.setWidth("102px");
		faxField.setHeight("-1px");
		faxField.setSecret(false);
		mainLayout.addComponent(faxField, "top:138.0px;left:580.0px;");
		
		// mobileField
		mobileField = new TextField();
		mobileField.setCaption("Móvil");
		mobileField.setImmediate(false);
		mobileField.setWidth("102px");
		mobileField.setHeight("-1px");
		mobileField.setSecret(false);
		mainLayout.addComponent(mobileField, "top:138.0px;left:699.0px;");
		
		// facebookField
		facebookIdField = new TextField();
		facebookIdField.setCaption("Facebook Id");
		facebookIdField.setImmediate(false);
		facebookIdField.setWidth("79px");
		facebookIdField.setHeight("-1px");
		facebookIdField.setSecret(false);
		mainLayout.addComponent(facebookIdField, "top:138.0px;left:821.0px;");
		
		return mainLayout;
	}
}
