package com.thingtrack.konekti.view.web.form;

import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceReference;

import com.thingtrack.konekti.domain.SupplierAgentType;
import com.thingtrack.konekti.service.api.SupplierAgentTypeService;
import com.thingtrack.konekti.view.addon.data.BindingSource;
import com.thingtrack.konekti.view.web.form.field.AddressField;
import com.thingtrack.konekti.view.web.form.field.ImageField;
import com.thingtrack.konekti.view.web.form.field.UserField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.validator.EmailValidator;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Select;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class SupplierAgentViewForm extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private UserField userField_1;
	@AutoGenerated
	private ImageField photoField;
	@AutoGenerated
	private CheckBox clientStatusField;
	@AutoGenerated
	private ComboBox supplierAgentTypeField;
	@AutoGenerated
	private TextField tittleField;
	@AutoGenerated
	private TextField surnameField;
	@AutoGenerated
	private TextField shortnameField;
	@AutoGenerated
	private TextField phoneField;
	@AutoGenerated
	private TextField nifField;
	@AutoGenerated
	private TextField nameField;
	@AutoGenerated
	private TextField mobileField;
	@AutoGenerated
	private TextField faxField;
	@AutoGenerated
	private TextField facebookIdField;
	@AutoGenerated
	private AddressField supplierAgentAddressField;
	@AutoGenerated
	private TextField emailField;
	@AutoGenerated
	private TextField commentField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private SupplierAgentTypeService supplierAgentTypeService;
	
	// organization type datasource
	private BeanItemContainer<SupplierAgentType> bcSupplierAgentType = new BindingSource<SupplierAgentType>(SupplierAgentType.class);
		
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 * @throws Exception 
	 * @throws IllegalArgumentException 
	 */
	public SupplierAgentViewForm() throws IllegalArgumentException, Exception {	
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		// configure Employee Agent Type data
		initComponents();
		
		// configure Employee Agent Type data
		supplierAgentTypeField.setItemCaptionMode(Select.ITEM_CAPTION_MODE_PROPERTY);
		supplierAgentTypeField.setItemCaptionPropertyId("description");
		
		// get form services from OSGi Service Registry
		getServices();
		
		// load data sources
		loadData();
	}
	
	private void initComponents() {
		tittleField.setNullRepresentation("");
		surnameField.setNullRepresentation("");
		shortnameField.setNullRepresentation("");
		phoneField.setNullRepresentation("");
		nifField.setNullRepresentation("");
		nameField.setNullRepresentation("");
		mobileField.setNullRepresentation("");
		faxField.setNullRepresentation("");
		facebookIdField.setNullRepresentation("");
		emailField.setNullRepresentation("");
		commentField.setNullRepresentation("");
		
		nameField.setRequiredError(nameField.getCaption() + " es un campo requerido");
		supplierAgentTypeField.setRequiredError(supplierAgentTypeField.getCaption() + " es un campo requerido");
		emailField.addValidator(new EmailValidator(emailField.getCaption() + " no es un correo electrónico válido"));
	}
	
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void getServices() {
		try {
			BundleContext bundleContext = FrameworkUtil.getBundle(ClientAgentViewForm.class).getBundleContext();
		
			ServiceReference supplierAgentTypeServiceReference = bundleContext.getServiceReference(SupplierAgentTypeService.class.getName());
			supplierAgentTypeService = SupplierAgentTypeService.class.cast(bundleContext.getService(supplierAgentTypeServiceReference));
			
		}
		catch (Exception e) {
			e.getMessage();
			
		}
		
	}
	
	private void loadData() throws IllegalArgumentException, Exception {
		bcSupplierAgentType.removeAllItems();
		bcSupplierAgentType.addAll(supplierAgentTypeService.getAll());		
		
		supplierAgentTypeField.setContainerDataSource(bcSupplierAgentType);
				
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("920px");
		mainLayout.setHeight("450px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("920px");
		setHeight("450px");
		
		// commentField
		commentField = new TextField();
		commentField.setCaption("Comentario");
		commentField.setImmediate(false);
		commentField.setWidth("880px");
		commentField.setHeight("61px");
		commentField.setTabIndex(16);
		commentField.setSecret(false);
		mainLayout.addComponent(commentField, "top:376.0px;left:15.0px;");
		
		// emailField
		emailField = new TextField();
		emailField.setCaption("Email");
		emailField.setImmediate(false);
		emailField.setWidth("427px");
		emailField.setHeight("-1px");
		emailField.setTabIndex(14);
		emailField.setSecret(false);
		mainLayout.addComponent(emailField, "top:333.0px;left:19.0px;");
		
		// supplierAgentAddressField
		supplierAgentAddressField = new AddressField();
		supplierAgentAddressField.setCaption("Dirección");
		supplierAgentAddressField.setImmediate(false);
		supplierAgentAddressField.setWidth("426px");
		supplierAgentAddressField.setHeight("130px");
		mainLayout.addComponent(supplierAgentAddressField,
				"top:178.0px;left:20.0px;");
		
		// facebookIdField
		facebookIdField = new TextField();
		facebookIdField.setCaption("Facebook Id");
		facebookIdField.setImmediate(false);
		facebookIdField.setWidth("140px");
		facebookIdField.setHeight("-1px");
		facebookIdField.setTabIndex(15);
		facebookIdField.setSecret(false);
		mainLayout.addComponent(facebookIdField, "top:322.0px;left:759.0px;");
		
		// faxField
		faxField = new TextField();
		faxField.setCaption("Fax");
		faxField.setImmediate(false);
		faxField.setWidth("140px");
		faxField.setHeight("-1px");
		faxField.setTabIndex(13);
		faxField.setSecret(false);
		mainLayout.addComponent(faxField, "top:280.0px;left:761.0px;");
		
		// mobileField
		mobileField = new TextField();
		mobileField.setCaption("Móvil personal");
		mobileField.setImmediate(false);
		mobileField.setWidth("140px");
		mobileField.setHeight("-1px");
		mobileField.setTabIndex(12);
		mobileField.setSecret(false);
		mainLayout.addComponent(mobileField, "top:240.0px;left:759.0px;");
		
		// nameField
		nameField = new TextField();
		nameField.setCaption("Nombre");
		nameField.setImmediate(false);
		nameField.setWidth("120px");
		nameField.setHeight("-1px");
		nameField.setTabIndex(5);
		nameField.setRequired(true);
		nameField.setSecret(false);
		mainLayout.addComponent(nameField, "top:92.0px;left:458.0px;");
		
		// nifField
		nifField = new TextField();
		nifField.setCaption("NIF");
		nifField.setImmediate(false);
		nifField.setWidth("92px");
		nifField.setHeight("-1px");
		nifField.setTabIndex(8);
		nifField.setSecret(false);
		mainLayout.addComponent(nifField, "top:138.0px;left:640.0px;");
		
		// phoneField
		phoneField = new TextField();
		phoneField.setCaption("Teléfono fijo");
		phoneField.setImmediate(false);
		phoneField.setWidth("140px");
		phoneField.setHeight("24px");
		phoneField.setTabIndex(11);
		phoneField.setSecret(false);
		mainLayout.addComponent(phoneField, "top:196.0px;left:759.0px;");
		
		// shortnameField
		shortnameField = new TextField();
		shortnameField.setCaption("Nombre corto");
		shortnameField.setImmediate(false);
		shortnameField.setWidth("169px");
		shortnameField.setHeight("24px");
		shortnameField.setTabIndex(7);
		shortnameField.setSecret(false);
		mainLayout.addComponent(shortnameField, "top:136.0px;left:458.0px;");
		
		// surnameField
		surnameField = new TextField();
		surnameField.setCaption("Apellidos");
		surnameField.setImmediate(false);
		surnameField.setWidth("306px");
		surnameField.setHeight("-1px");
		surnameField.setTabIndex(6);
		surnameField.setSecret(false);
		mainLayout.addComponent(surnameField, "top:92.0px;left:589.0px;");
		
		// tittleField
		tittleField = new TextField();
		tittleField.setCaption("Trat.");
		tittleField.setImmediate(false);
		tittleField.setWidth("40px");
		tittleField.setHeight("-1px");
		tittleField.setTabIndex(4);
		tittleField.setSecret(false);
		mainLayout.addComponent(tittleField, "top:48.0px;left:458.0px;");
		
		// supplierAgentTypeField
		supplierAgentTypeField = new ComboBox();
		supplierAgentTypeField.setCaption("Tipo proveedor");
		supplierAgentTypeField.setImmediate(false);
		supplierAgentTypeField.setWidth("149px");
		supplierAgentTypeField.setHeight("-1px");
		supplierAgentTypeField.setTabIndex(9);
		supplierAgentTypeField.setRequired(true);
		mainLayout.addComponent(supplierAgentTypeField,
				"top:140.0px;left:746.0px;");
		
		// clientStatusField
		clientStatusField = new CheckBox();
		clientStatusField.setCaption("Activo");
		clientStatusField.setImmediate(false);
		clientStatusField.setWidth("-1px");
		clientStatusField.setHeight("-1px");
		clientStatusField.setTabIndex(3);
		mainLayout.addComponent(clientStatusField, "top:49.0px;left:842.0px;");
		
		// photoField
		photoField = new ImageField();
		photoField.setImmediate(false);
		photoField.setWidth("426px");
		photoField.setHeight("139px");
		mainLayout.addComponent(photoField, "top:23.0px;left:20.0px;");
		
		// userField_1
		userField_1 = new UserField();
		userField_1.setImmediate(false);
		userField_1.setWidth("283px");
		userField_1.setHeight("180px");
		mainLayout.addComponent(userField_1, "top:178.0px;left:458.0px;");
		
		return mainLayout;
	}
}