package com.thingtrack.konekti.view.module.alarm.internal;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;

import org.quartz.Scheduler;
import org.springframework.beans.factory.annotation.Autowired;

import com.thingtrack.konekti.service.api.JobService;
import com.thingtrack.konekti.service.api.AlarmService;
import com.thingtrack.konekti.view.addon.ui.AbstractViewContainer;
import com.thingtrack.konekti.view.addon.ui.SliderView;
import com.thingtrack.konekti.view.kernel.IWorkbenchContext;
import com.thingtrack.konekti.view.kernel.ui.layout.ISliderView;
import com.thingtrack.konekti.view.kernel.ui.layout.IViewChangeListener;
import com.thingtrack.konekti.view.kernel.ui.layout.IView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class AlarmViewContainer extends AbstractViewContainer {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private SliderView sliderView;

	/** Views **/
	private AlarmView alarmView;
	private JobView jobView;
	
	/** Business services **/
	@Autowired
	private AlarmService alarmService;	
	@Autowired
	private JobService jobService;
	@Autowired	
	private Scheduler scheduler;
	
	// Thread Local Bundle Business Services
	private static ThreadLocal<AlarmService> threadAlarmService = new ThreadLocal<AlarmService>();
	private static ThreadLocal<JobService> threadJobService = new ThreadLocal<JobService>();
	private static ThreadLocal<Scheduler> threadScheduler = new ThreadLocal<Scheduler>();
	
	private IWorkbenchContext context; 
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AlarmViewContainer(IWorkbenchContext context) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.context = context;
	}
	
	@SuppressWarnings("unused")
	@PostConstruct
	private void createViews() {
		// initialize thread local bundle services
		threadAlarmService.set(alarmService);
		threadJobService.set(jobService);
		threadScheduler.set(scheduler);
		
		// add all views controlled by SliderView Component
		alarmView = new AlarmView(context, this);
		sliderView.addView(alarmView);
		views.put(0, alarmView);
		
		jobView = new JobView(context, this);
		sliderView.addView(jobView);
		views.put(1, jobView);
	}
		
	@SuppressWarnings("unused")
	@PreDestroy
	private void destroyViews() {
		// destroy thread local bundle services
		threadAlarmService.set(null);
		threadJobService.set(null);
		threadScheduler.set(null);
	}
	
    public static AlarmService getAlarmService() {
        return threadAlarmService.get();
        
    }
    	
    public static JobService getJobService() {
        return threadJobService.get();
        
    }
    
    public static Scheduler getScheduler() {
        return threadScheduler.get();
        
    }
    
	@Override
	public ISliderView getSliderView() {
		return sliderView;
		
	}
	
	@Override
	public IView getSelectedView() {
		return sliderView.getSelectedView();
		
	}
	
	@Override
	public void addListener(IViewChangeListener listener) {
		sliderView.addListener(listener);
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// sliderView
		sliderView = new SliderView();
		sliderView.setImmediate(false);
		sliderView.setWidth("100.0%");
		sliderView.setHeight("100.0%");
		mainLayout.addComponent(sliderView);
		mainLayout.setExpandRatio(sliderView, 1.0f);
		
		return mainLayout;
	}
}
