package com.thingtrack.konekti.view.module.alarm.internal;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import org.vaadin.dialogs.ConfirmDialog;

import com.thingtrack.konekti.domain.Job;
import com.thingtrack.konekti.schedule.JobManagerService;
import com.thingtrack.konekti.service.api.JobService;
import com.thingtrack.konekti.view.addon.data.BindingSource;
import com.thingtrack.konekti.view.addon.ui.AbstractView;
import com.thingtrack.konekti.view.addon.ui.BoxToolbar;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar;
import com.thingtrack.konekti.view.addon.ui.BoxToolbar.ClickFilterButtonListener;
import com.thingtrack.konekti.view.addon.ui.BoxToolbar.ClickNavigationEvent;
import com.thingtrack.konekti.view.addon.ui.BoxToolbar.ClickPrintButtonListener;
import com.thingtrack.konekti.view.addon.ui.DataGridView;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar.ClickAddButtonListener;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar.ClickEditButtonListener;
import com.thingtrack.konekti.view.addon.ui.EditionToolbar.ClickRemoveButtonListener;
import com.thingtrack.konekti.view.addon.ui.NavigationToolbar;
import com.thingtrack.konekti.view.addon.ui.NavigationToolbar.ClickRefreshButtonListener;
import com.thingtrack.konekti.view.addon.ui.NavigationToolbar.ClickUpButtonListener;
import com.thingtrack.konekti.view.addon.ui.WindowDialog;
import com.thingtrack.konekti.view.addon.ui.WindowDialog.DialogResult;
import com.thingtrack.konekti.view.kernel.IWorkbenchContext;
import com.thingtrack.konekti.view.kernel.ui.layout.IViewContainer;
import com.thingtrack.konekti.view.module.alarm.addon.JobToolbar;
import com.thingtrack.konekti.view.module.alarm.addon.JobToolbar.ClickStartJobButtonListener;
import com.thingtrack.konekti.view.module.alarm.addon.JobToolbar.ClickStopJobButtonListener;
import com.thingtrack.konekti.view.web.form.JobViewForm;
import com.vaadin.data.Property;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomTable;
import com.vaadin.ui.Field;
import com.vaadin.ui.Label;
import com.vaadin.ui.TableFieldFactory;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.CustomTable.ColumnGenerator;

@SuppressWarnings("serial")
public class JobView extends AbstractView 
	implements ClickRefreshButtonListener, ClickAddButtonListener, ClickEditButtonListener, 
	           ClickRemoveButtonListener, ClickFilterButtonListener, ClickPrintButtonListener,
	           ClickUpButtonListener, ClickStartJobButtonListener, ClickStopJobButtonListener {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private DataGridView dgJob;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private JobService jobService;
	
	private BindingSource<Job> bsJob = new BindingSource<Job>(Job.class, 1);
	
	private NavigationToolbar navigationToolbar;
	private EditionToolbar editionToolbar;
	private BoxToolbar boxToolbar;
	private JobToolbar jobToolbar;
	
	private IWorkbenchContext context;
	private IViewContainer viewContainer;
	
	private JobManagerService jobManagerService;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public JobView(IWorkbenchContext context, IViewContainer viewContainer) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here		
		// set Slide View Services and ViewContainer to navigate
		this.context = context;
		this.viewContainer = viewContainer;
		
		this.jobService = AlarmViewContainer.getJobService();
		this.jobManagerService = AlarmViewContainer.getJobManagerService();
		
		// initialize datasource views
		initView();
	}

	private void initView() {
		// initialize Slide View Organization View
		dgJob.setImmediate(true);

		refreshBindindSource();

		// STEP 01: create grid view for slide Organization View
		try {
			dgJob.setBindingSource(bsJob);
			dgJob.addGeneratedColumn(JobNameColumn.JOB_NAME_COLUMN_ID, new JobNameColumn());
			dgJob.addGeneratedColumn(JobTriggerTypeColumn.JOB_TRIGGER_TYPE_DESCRIPTION_COLUMN_ID, new JobTriggerTypeColumn());
			dgJob.setVisibleColumns(new String[] {JobNameColumn.JOB_NAME_COLUMN_ID, "jobName", "jobGroup", "description", JobTriggerTypeColumn.JOB_TRIGGER_TYPE_DESCRIPTION_COLUMN_ID, "jobTriggerPriority",
					"startTime", "endTime", "jobInterval", "repeatCount", "jobCalendar", "future", "future_time", "cronExpression", "lastExecution", "error", "active" });
			dgJob.setColumnHeaders(new String[] { "Ubicación", "Nombre", "Grupo", "Descripción", "Tipo Disparador", "Prioridad Disparador", "Fecha Comienzo", "Fecha Fin",
					"Intervalo [s]", "Repetición", "Calendario", "Futuro", "Fecha Futuro", "Expresión Cron", "Ultima Ejecución", "Error", "Activa"});			
			dgJob.setEditable(true);
			
			dgJob.setColumnCollapsed("jobTriggerType.description", true);
			dgJob.setColumnCollapsed("jobTriggerPriority", true);
			//dgJob.setColumnCollapsed("startTime", true);
			//dgJob.setColumnCollapsed("endTime", true);
			dgJob.setColumnCollapsed("jobInterval", true);
			dgJob.setColumnCollapsed("repeatCount", true);
			dgJob.setColumnCollapsed("jobCalendar", true);
			dgJob.setColumnCollapsed("future", true);
			dgJob.setColumnCollapsed("future_time", true);
			dgJob.setColumnCollapsed("cronExpression", true);
			
			dgJob.setTableFieldFactory(new TableFieldFactory() {					
				@Override
				public Field createField(Container container, Object itemId,
						Object propertyId, Component uiContext) {
					if("active".equals(propertyId) || "error".equals(propertyId) || "future".equals(propertyId)) {						
						CheckBox field = new CheckBox();
						field.setReadOnly(true);						
						return field;
					}
					
					return null;
				}
			});
			
		} catch (Exception ex) {
			ex.getMessage();
		}

		// STEP 02: create toolbar for slide Employee Agent View
		navigationToolbar = new NavigationToolbar(0, bsJob, viewContainer);
		editionToolbar = new EditionToolbar(1, bsJob);
		boxToolbar = new BoxToolbar(2, bsJob);		
		jobToolbar = new JobToolbar(3, bsJob, viewContainer);
		
		navigationToolbar.addListenerRefreshButton(this);
		navigationToolbar.addListenerUpButton(this);
		
		editionToolbar.addListenerAddButton(this);
		editionToolbar.addListenerEditButton(this);
		editionToolbar.addListenerDeleteButton(this);
		editionToolbar.setPermission(context.getUser(), viewContainer.getModule().getSymbolicName(), viewContainer.getModule().getVersion());
		
		boxToolbar.addListenerFilterButton(this);
		boxToolbar.addListenerPrintButton(this);

		jobToolbar.addListenerStartJobButton(this);
		jobToolbar.addListenerStopJobButton(this);
		
		dgJob.addListenerAddButton(this);
		dgJob.addListenerEditButton(this);
		dgJob.addListenerDeleteButton(this);
		
		removeAllToolbar();

		addToolbar(navigationToolbar);
		addToolbar(editionToolbar);
		addToolbar(boxToolbar);
		addToolbar(jobToolbar);

	}
	
	private void refreshBindindSource() {
		try {
			bsJob.removeAllItems();
			bsJob.addAll(jobService.getAll(context.getUser()));
			
			bsJob.addNestedContainerProperty("jobTriggerType.description");
		} catch (IllegalArgumentException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	public void upButtonClick(NavigationToolbar.ClickNavigationEvent event) {
		viewContainer.getSliderView().rollPrevious();
		
	}
	
	@Override
	public void refreshButtonClick(NavigationToolbar.ClickNavigationEvent event) {
		refreshBindindSource();
		
	}
	
	private void refreshDataGridView(Job jobSaved) {
		if(bsJob.containsId(jobSaved)){			
			Job previousJob= bsJob.prevItemId(jobSaved);
			
			bsJob.removeItem(jobSaved);
			bsJob.addItemAfter(previousJob, jobSaved);
			bsJob.setItemId(jobSaved);
		}
		else
			bsJob.addItem(jobSaved);
		
	}
	
	@Override
	public void addButtonClick(EditionToolbar.ClickNavigationEvent event) {
		Job job = null;
		try {
			job = jobService.createNewEntity(context.getUser().getActiveArea());
		} catch (Exception e) {
			throw new RuntimeException("¡No se pudo crear la entidad job!", e);
			
		}
		
		try {
			@SuppressWarnings("unused")
			WindowDialog<Job> windowDialog = new WindowDialog<Job>(getWindow(), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.add.tittle"), 
					getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.button.left"), DialogResult.SAVE, getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.button.right"), DialogResult.CANCEL, 
					new JobViewForm(), job, 
					new WindowDialog.CloseWindowDialogListener<Job>() {
			    public void windowDialogClose(WindowDialog<Job>.CloseWindowDialogEvent<Job> event) {
			    	if (event.getDialogResult() != WindowDialog.DialogResult.SAVE)
			    		return ;
			    	
			    		final Job savingjob= event.getDomainEntity();
			    		
			    		// STEP01: schedule new job	
			    		try {
			    			jobManagerService.scheduleJob(savingjob);
			    			
			    		} catch (Exception e) {
			    			ConfirmDialog.show(getWindow(), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.add.tittle"),
									getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.add.confirmation"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.add.confirmation.yes"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.add.confirmation.no"),
							        new ConfirmDialog.Listener() {

							            public void onClose(ConfirmDialog dialog) {
							                if (dialog.isConfirmed()) {
							                	// STEP02: save new job scheduled
									    		Job savedJob;
												try {
													savedJob = jobService.save(savingjob);
													refreshDataGridView(savedJob);
												} catch (Exception e) {
													throw new RuntimeException("¡No se pudo crear la nueva job!", e);
													
												}

							                }
							            }
							        });
			    			
			    		}

			    }

			});
		} catch (Exception e) {
			throw new RuntimeException("¡No se pudo abrir el formulario Nuevo Job!", e);
		}
		
	}
	
	@Override
	public void editButtonClick(EditionToolbar.ClickNavigationEvent event) {
		Job editingJob = (Job) event.getRegister();
		
		try {
			@SuppressWarnings("unused")
			WindowDialog<Job> windowDialog = new WindowDialog<Job>(getWindow(), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.edit.tittle"), 
					getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.button.left"), DialogResult.SAVE, getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.button.right"), DialogResult.CANCEL, 
					new JobViewForm(), editingJob, 
					new WindowDialog.CloseWindowDialogListener<Job>() {
			    public void windowDialogClose(WindowDialog<Job>.CloseWindowDialogEvent<Job> event) {
			    	if (event.getDialogResult() != WindowDialog.DialogResult.SAVE)
			    		return ;
			    				    		
			    		final Job savingJob = event.getDomainEntity();			    		
			    		
				    	ConfirmDialog.show(getWindow(), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.edit.tittle"),
								getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.edit.confirmation"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.edit.confirmation.yes"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.edit.confirmation.no"),
						        new ConfirmDialog.Listener() {

						            public void onClose(ConfirmDialog dialog) {
						                if (!dialog.isConfirmed()) {
						                	try {
												Job job = jobService.get(savingJob.getJobId());
												
												refreshDataGridView(job);
											} catch (Exception e) {
												throw new RuntimeException("¡No se pudo recuperar el job seleccionado!", e);
											}
						                							            	
						                }
						                else {
						                	// STEP01: reschedule job	
								    		try {
								    			jobManagerService.configure(savingJob);
								    		} catch (Exception e) {
								    			throw new RuntimeException("¡No se pudo parar el job seleccionado!", e);
								    		}
								    		
								    		// STEP02: save job status rescheduled
								    		Job savedJob;
											try {
												savedJob = jobService.save(savingJob);
												
												refreshDataGridView(savedJob);
											} catch (Exception e) {
												throw new RuntimeException("¡No se pudo modificar el job!", e);
											}			    		
								    		
											
						                }
						                 
						            }
						        });
				    	
			    }

			});
		} catch (IllegalArgumentException e) {
			throw new RuntimeException("¡No se pudo abrir el formulario Editor Job!", e);
		} catch (Exception e) {
			throw new RuntimeException("¡No se pudo abrir el formulario Editor Job!", e);
		}
	}
	
	@Override
	public void deleteButtonClick(EditionToolbar.ClickNavigationEvent event) {
		final Job editingJob = (Job) event.getRegister();
		
		if (editingJob == null)
			return;
		
		ConfirmDialog.show(getWindow(), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.remove.tittle"),
				getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.remove.confirmation"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.remove.confirmation.yes"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.windowDialog.remove.confirmation.no"),
		        new ConfirmDialog.Listener() {

		            public void onClose(ConfirmDialog dialog) {
		                if (dialog.isConfirmed()) {
		            		try {
					    		// STEP01: unschedule job	
					    		try {
					    			jobManagerService.deleteJob(editingJob);
					    		} catch (Exception e) {
					    			ConfirmDialog.show(getWindow(), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.remove.tittle"),
											getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.remove.confirmation"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.remove.confirmation.yes"), getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.AlarmView.windowDialog.edit.confirmation.no"),
									        new ConfirmDialog.Listener() {

									            public void onClose(ConfirmDialog dialog) {
									                if (dialog.isConfirmed()) {
														try {
															// STEP02: remove job unscheduled
									            			jobService.delete(editingJob);
									            			
									            			bsJob.removeItem(editingJob);
									            			
														} catch (Exception e) {
															throw new RuntimeException("¡No se pudo borrar el job!", e);
														}

									                }
									            }
									        });
					    			
					    		}
					    		            			
		            		} catch (IllegalArgumentException e) {
		            			throw new RuntimeException("¡No se pudo borrar el job!", e);
		            		} catch (Exception e) {
		            			throw new RuntimeException("¡No se pudo borrar el job!", e);
		            		}
		                } 
		            }
		        });
		
	}

	@Override
	public void filterButtonClick(ClickNavigationEvent event) {
		dgJob.setFilterBarVisible();
		
	}
	
	@Override
	public void printButtonClick(ClickNavigationEvent event) {
		try {
			dgJob.print("Listado Jobs");
			
		}
		catch (Exception e) {
			throw new RuntimeException("¡No se pudo imprimir el informe!", e);
		}
			
	}
	
	@Override
	public void startJobButtonClick(JobToolbar.ClickNavigationEvent event) {
		Job job = (Job) event.getRegister();		
		
		// STEP01: start job from scheduler		
		try {
			jobManagerService.resumeJob(job);
		} catch (Exception e) {
			throw new RuntimeException("¡No se pudo iniciar el job seleccionado!", e);
		}
		
		// STEP02: save job status started
		try {
			job.setActive(true);			
			jobService.save(job);
			
			refreshDataGridView(job);
		} catch (Exception e) {
			throw new RuntimeException("¡No se pudo modificar el estado del job iniciado!", e);
			
		}
							
	}
	
	@Override
	public void stopJobButtonClick(JobToolbar.ClickNavigationEvent event) {
		Job job = (Job) event.getRegister();		
		
		// STEP01: stop job from scheduler		
		try {
			jobManagerService.pauseJob(job);
		} catch (Exception e) {
			throw new RuntimeException("¡No se pudo parar el job seleccionado!", e);
		}
		
		// STEP02: save job status stopped
		try {
			job.setActive(false);
			jobService.save(job);
			
			refreshDataGridView(job);
		} catch (Exception e) {
			throw new RuntimeException("¡No se pudo modificar el estado del job parado!", e);
		}
				
	}
	
	private class JobNameColumn implements ColumnGenerator {

		static final String JOB_NAME_COLUMN_ID = "job_name_column-id";
		
		@Override
		public Object generateCell(CustomTable source, Object itemId, Object columnId) {
			
			Label jobNameLabel = new Label();
			
			Job job = (Job) itemId;
			
			if(job.getArea() != null)
				jobNameLabel.setValue(job.getArea().getName());
			
			return jobNameLabel;
		}
				
	}
	
	private class JobTriggerTypeColumn implements ColumnGenerator {

		static final String JOB_TRIGGER_TYPE_DESCRIPTION_COLUMN_ID = "job-trigger-type-description-column-id";
		
		@Override
		public Object generateCell(CustomTable source, Object itemId, Object columnId) {
			
			Label jobTriggerType = new Label();
			
			Job job = (Job) itemId;
			
			if(job.getJobTriggerType() != null)
				jobTriggerType.setValue(job.getJobTriggerType().getDescription());
			
			return jobTriggerType;
		}
				
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// dataGridView_1
		dgJob = new DataGridView() {
			@Override
			protected String formatPropertyValue(Object rowId, Object colId, Property property) {
				if (property != null && (property.getType() == Date.class || property.getType() == Calendar.class)) {
					SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

					if (property.getType() == Date.class && property.getValue() != null)
						return df.format((Date) property.getValue());
					else  {
						if (property.getType() == Calendar.class && property.getValue() != null)
							return df.format(((Calendar) property.getValue()).getTime());
						else
							return super.formatPropertyValue(rowId, colId, property);
					}
					
				}

				return super.formatPropertyValue(rowId, colId, property);
			}
		};
		
		dgJob.setImmediate(false);
		dgJob.setWidth("100.0%");
		dgJob.setHeight("100.0%");
		mainLayout.addComponent(dgJob);
		mainLayout.setExpandRatio(dgJob, 1.0f);
		
		return mainLayout;
	}

	@Override
	protected void updateLabels() {
		dgJob.setColumnHeaders(new String[] { getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.area.description"), 
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.jobName"), 
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.jobGroup"), 
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.description"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.jobTriggerTypeName"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.jobTriggerPriority"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.startTime"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.endTime"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.jobInterval"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.repeatCount"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.jobCalendar"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.future"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.future_time"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.cronExpression"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.lastExecution"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.error"),
				  getI18N().getMessage("com.thingtrack.konekti.view.module.alarm.internal.JobView.dgJob.column.active")});
		
	}

}
